import os
import re
import uuid
import html
from config import Config

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

EXPORT_FOLDER = Config.EXPORT_FOLDER
os.makedirs(EXPORT_FOLDER, exist_ok=True)


# =====================================
# UNICODE & XML SANITIZATION FOR REPORTLAB
# =====================================

def sanitize_for_pdf(text):
    """Normalize and escape text for safe ReportLab XML parsing without font mapping errors."""
    if not text:
        return ""

    # Common unicode replacements to prevent Helvetica encoding errors
    replacements = {
        "\u2013": "-",    # En-dash
        "\u2014": "--",   # Em-dash
        "\u2011": "-",    # Non-breaking hyphen
        "\u2018": "'",    # Left single quote
        "\u2019": "'",    # Right single quote
        "\u201c": '"',    # Left double quote
        "\u201d": '"',    # Right double quote
        "\u2022": "*",    # Bullet
        "\u2026": "...",  # Ellipsis
        "\u00a0": " ",    # Non-breaking space
        "\u2192": "->",   # Right arrow
        "\u2190": "<-",   # Left arrow
        "\u2264": "<=",   # Less than or equal
        "\u2265": ">=",   # Greater than or equal
        "\u2260": "!=",   # Not equal
        "\u00b1": "+/-",  # Plus-minus
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)

    # Escape HTML special characters
    text = html.escape(text)

    # Re-enable basic styling tags if present in markdown
    # Convert bold **text** to <b>text</b>
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Convert italic *text* to <i>text</i>
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", text)
    # Convert `code` to <code>code</code>
    text = re.sub(r"`(.+?)`", r"<font face='Courier' color='#0f766e'>\1</font>", text)

    return text


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to calculate total page count and render running headers and footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(54, 750, "AI Research Report | Confidential & Academic Use")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Footer (all pages)
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, footer_text)
        self.drawString(54, 36, "Generated by AI Research Assistant (Powered by Groq)")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)

        self.restoreState()


# =====================================
# CREATE PDF
# =====================================

def create_pdf(report_text, title=None):
    """Generate a publication-grade, beautifully formatted PDF report."""
    try:
        filename = os.path.join(
            EXPORT_FOLDER,
            f"Research_Report_{uuid.uuid4().hex[:8]}.pdf"
        )

        doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Custom typography styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=12
        )

        h1_style = ParagraphStyle(
            "DocH1",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=19,
            textColor=colors.HexColor("#1E3A8A"),
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        )

        h2_style = ParagraphStyle(
            "DocH2",
            parent=styles["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#0369A1"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=6
        )

        bullet_style = ParagraphStyle(
            "DocBullet",
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        meta_style = ParagraphStyle(
            "DocMeta",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=14
        )

        story = []

        # Document Header
        report_title = title if title else "AI Academic Research Report"
        story.append(Paragraph(sanitize_for_pdf(report_title), title_style))
        story.append(Paragraph("AI Research Assistant &bull; Generated with Groq LLM", meta_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#2563EB"), spaceAfter=14))

        # Parse lines
        for raw_line in report_text.splitlines():
            line = raw_line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue

            # Heading 1 (# or ##)
            if line.startswith("# ") or line.startswith("## "):
                clean_heading = re.sub(r"^#+\s*", "", line)
                story.append(Paragraph(sanitize_for_pdf(clean_heading), h1_style))
            # Heading 2 (###)
            elif line.startswith("### "):
                clean_heading = re.sub(r"^###\s*", "", line)
                story.append(Paragraph(sanitize_for_pdf(clean_heading), h2_style))
            # Bullet point (- or * or •)
            elif line.startswith(("- ", "* ", "• ")):
                bullet_text = re.sub(r"^[\-\*\•]\s*", "&bull; ", line)
                story.append(Paragraph(sanitize_for_pdf(bullet_text), bullet_style))
            # Numbered list
            elif re.match(r"^\d+\.\s", line):
                story.append(Paragraph(sanitize_for_pdf(line), bullet_style))
            # Horizontal Rule
            elif line in ("---", "***", "___"):
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1"), spaceBefore=8, spaceAfter=8))
            # Regular paragraph
            else:
                story.append(Paragraph(sanitize_for_pdf(line), body_style))

        doc.build(story, canvasmaker=NumberedCanvas)
        return filename

    except Exception as e:
        raise Exception(f"PDF export failed: {str(e)}")


# =====================================
# CREATE WORD DOCUMENT (.DOCX)
# =====================================

def create_docx(report_text, title=None):
    """Generate an executive-formatted Microsoft Word .docx file."""
    try:
        filename = os.path.join(
            EXPORT_FOLDER,
            f"Research_Report_{uuid.uuid4().hex[:8]}.docx"
        )

        doc = Document()

        # Set standard margins (1 inch)
        for section in doc.sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)

        # Title
        report_title = title if title else "AI Academic Research Report"
        title_para = doc.add_paragraph()
        title_run = title_para.add_run(report_title)
        title_run.font.name = "Calibri"
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(15, 23, 42)
        title_para.paragraph_format.space_after = Pt(4)

        # Subtitle
        sub_para = doc.add_paragraph()
        sub_run = sub_para.add_run("Generated by AI Research Assistant | Powered by Groq AI")
        sub_run.font.name = "Calibri"
        sub_run.font.size = Pt(10)
        sub_run.font.italic = True
        sub_run.font.color.rgb = RGBColor(100, 116, 139)
        sub_para.paragraph_format.space_after = Pt(18)

        # Parse lines
        for raw_line in report_text.splitlines():
            line = raw_line.strip()
            if not line:
                continue

            if line.startswith("# "):
                clean = re.sub(r"^#\s*", "", line)
                h = doc.add_heading(clean, level=1)
                h.paragraph_format.space_before = Pt(14)
                h.paragraph_format.space_after = Pt(6)
            elif line.startswith("## "):
                clean = re.sub(r"^##\s*", "", line)
                h = doc.add_heading(clean, level=2)
                h.paragraph_format.space_before = Pt(12)
                h.paragraph_format.space_after = Pt(4)
            elif line.startswith("### "):
                clean = re.sub(r"^###\s*", "", line)
                h = doc.add_heading(clean, level=3)
                h.paragraph_format.space_before = Pt(8)
                h.paragraph_format.space_after = Pt(2)
            elif line.startswith(("- ", "* ", "• ")):
                clean = re.sub(r"^[\-\*\•]\s*", "", line)
                doc.add_paragraph(clean, style="List Bullet")
            elif re.match(r"^\d+\.\s", line):
                clean = re.sub(r"^\d+\.\s*", "", line)
                doc.add_paragraph(clean, style="List Number")
            elif line in ("---", "***", "___"):
                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(6)
                p.paragraph_format.space_after = Pt(6)
            else:
                p = doc.add_paragraph(line)
                p.paragraph_format.space_after = Pt(6)
                p.paragraph_format.line_spacing = 1.15

        doc.save(filename)
        return filename

    except Exception as e:
        raise Exception(f"Word (.docx) export failed: {str(e)}")


# =====================================
# CREATE MARKDOWN FILE (.MD)
# =====================================

def create_markdown(report_text, title=None):
    """Export raw report text as a clean Markdown .md file."""
    try:
        filename = os.path.join(
            EXPORT_FOLDER,
            f"Research_Report_{uuid.uuid4().hex[:8]}.md"
        )
        with open(filename, "w", encoding="utf-8") as f:
            if title:
                f.write(f"# {title}\n\n")
            f.write(report_text)
        return filename
    except Exception as e:
        raise Exception(f"Markdown export failed: {str(e)}")