from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.dml.color import RGBColor
import os
import uuid

OUTPUT_FOLDER = "generated_ppt"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


def create_presentation(title, slides):

    prs = Presentation()

    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # -----------------------------------
    # TITLE SLIDE
    # -----------------------------------

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    title_box = slide.shapes.add_textbox(
        Inches(0.8),
        Inches(1.2),
        Inches(11),
        Inches(1)
    )

    tf = title_box.text_frame

    p = tf.paragraphs[0]

    p.text = title

    p.font.size = Pt(30)

    p.font.bold = True

    p.font.color.rgb = RGBColor(0, 51, 102)

    p.alignment = PP_ALIGN.CENTER

    sub_box = slide.shapes.add_textbox(
        Inches(1),
        Inches(2.2),
        Inches(10),
        Inches(1)
    )

    tf = sub_box.text_frame

    p = tf.paragraphs[0]

    p.text = "Generated by AI Research Assistant"

    p.font.size = Pt(20)

    p.alignment = PP_ALIGN.CENTER

    p.font.color.rgb = RGBColor(100, 100, 100)

    # -----------------------------------
    # CONTENT SLIDES
    # -----------------------------------

    for i, item in enumerate(slides, start=1):

        slide = prs.slides.add_slide(prs.slide_layouts[6])

        # Blue Header
        header = slide.shapes.add_shape(
            MSO_AUTO_SHAPE_TYPE.RECTANGLE,
            0,
            0,
            prs.slide_width,
            Inches(0.7)
        )

        header.fill.solid()

        header.fill.fore_color.rgb = RGBColor(0, 76, 153)

        header.line.color.rgb = RGBColor(0, 76, 153)

        title_box = slide.shapes.add_textbox(
            Inches(0.4),
            Inches(0.1),
            Inches(11),
            Inches(0.4)
        )

        tf = title_box.text_frame

        p = tf.paragraphs[0]

        p.text = item["title"]

        p.font.bold = True

        p.font.size = Pt(24)

        p.font.color.rgb = RGBColor(255, 255, 255)

        body = slide.shapes.add_textbox(
            Inches(0.8),
            Inches(1.0),
            Inches(11.2),
            Inches(5.2)
        )

        tf = body.text_frame

        for index, point in enumerate(item["points"]):

            if index == 0:

                para = tf.paragraphs[0]

            else:

                para = tf.add_paragraph()

            para.text = point

            para.level = 0

            para.font.size = Pt(20)

            para.font.color.rgb = RGBColor(40, 40, 40)

        # Footer
        footer = slide.shapes.add_textbox(
            Inches(11.6),
            Inches(6.8),
            Inches(1),
            Inches(0.3)
        )

        p = footer.text_frame.paragraphs[0]

        p.text = str(i)

        p.alignment = PP_ALIGN.RIGHT

        p.font.size = Pt(12)

    filename = f"{uuid.uuid4().hex}.pptx"

    filepath = os.path.join(OUTPUT_FOLDER, filename)

    prs.save(filepath)

    return filepath